// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/hello.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest_Sex int32

const (
	HelloRequest_MALE   HelloRequest_Sex = 0
	HelloRequest_FEMALE HelloRequest_Sex = 1
	HelloRequest_OTHER  HelloRequest_Sex = 1
)

// Enum value maps for HelloRequest_Sex.
var (
	HelloRequest_Sex_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
		// Duplicate value: 1: "OTHER",
	}
	HelloRequest_Sex_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
		"OTHER":  1,
	}
)

func (x HelloRequest_Sex) Enum() *HelloRequest_Sex {
	p := new(HelloRequest_Sex)
	*p = x
	return p
}

func (x HelloRequest_Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HelloRequest_Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hello_proto_enumTypes[0].Descriptor()
}

func (HelloRequest_Sex) Type() protoreflect.EnumType {
	return &file_proto_hello_proto_enumTypes[0]
}

func (x HelloRequest_Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HelloRequest_Sex.Descriptor instead.
func (HelloRequest_Sex) EnumDescriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{0, 0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex           int32                  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Home          *Home                  `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *HelloRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *HelloRequest) GetHome() *Home {
	if x != nil {
		return x.Home
	}
	return nil
}

type HelloResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	mi := &file_proto_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_hello_proto protoreflect.FileDescriptor

const file_proto_hello_proto_rawDesc = "" +
	"\n" +
	"\x11proto/hello.proto\x12\x05hello\x1a\x10proto/home.proto\"\x94\x01\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sex\x18\x02 \x01(\x05R\x03sex\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1e\n" +
	"\x04home\x18\x04 \x01(\v2\n" +
	".home.HomeR\x04home\"*\n" +
	"\x03Sex\x12\b\n" +
	"\x04MALE\x10\x00\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x01\x12\t\n" +
	"\x05OTHER\x10\x01\x1a\x02\x10\x01\"%\n" +
	"\tHelloResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2>\n" +
	"\aGreeter\x123\n" +
	"\bSayHello\x12\x13.hello.HelloRequest\x1a\x10.hello.HelloResp\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_hello_proto_rawDescOnce sync.Once
	file_proto_hello_proto_rawDescData []byte
)

func file_proto_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)))
	})
	return file_proto_hello_proto_rawDescData
}

var file_proto_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_hello_proto_goTypes = []any{
	(HelloRequest_Sex)(0), // 0: hello.HelloRequest.Sex
	(*HelloRequest)(nil),  // 1: hello.HelloRequest
	(*HelloResp)(nil),     // 2: hello.HelloResp
	(*Home)(nil),          // 3: home.Home
}
var file_proto_hello_proto_depIdxs = []int32{
	3, // 0: hello.HelloRequest.home:type_name -> home.Home
	1, // 1: hello.Greeter.SayHello:input_type -> hello.HelloRequest
	2, // 2: hello.Greeter.SayHello:output_type -> hello.HelloResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hello_proto_init() }
func file_proto_hello_proto_init() {
	if File_proto_hello_proto != nil {
		return
	}
	file_proto_home_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_proto_depIdxs,
		EnumInfos:         file_proto_hello_proto_enumTypes,
		MessageInfos:      file_proto_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_proto = out.File
	file_proto_hello_proto_goTypes = nil
	file_proto_hello_proto_depIdxs = nil
}
